version: '3'

services:
  h5ai:
    image: awesometic/h5ai
    container_name: h5ai
    restart: always
    volumes:
      - ./config:/config
      # - /mnt/googledrive:/h5ai
    environment:
      - TZ=Asia/Shanghai # timezone
      # - HTPASSWD=true
      # - HTPASSWD_USER=admin
    ports:
      - 182:80
