version: "3"

services:
  h5ai:
    image: awesometic/h5ai
    container_name: h5ai
    restart: always
    volumes:
      - "./config:/config"
      # - "/mnt/googledrive:/h5ai"
    ports:
      - "185:80"
    environment:
      - TZ=Asia/Shanghai # timezone