version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwardenrs
    restart: always
    ports:
      - 184:80
      # websocket 通知端口
      # https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-WebSocket-notifications
      # - 185:3012
    volumes:
      - ./data:/data
    environment:
      - DOMAIN=your_domain
      - SIGNUPS_ALLOWED=false # 禁用注册
      - ADMIN_TOKEN=your_token # 开启 /admin 管理界面，更改为你的 token
      - LOG_FILE=/data/bitwarden.log # log
      - LOG_LEVEL=warn # log 级别：trace | debug | info | warn | error | off
      - EXTENDED_LOGGING=true
      # - WEBSOCKET_ENABLED=true