version: "3"
services:
  rsshub:
    image: diygod/rsshub
    container_name: rsshub
    restart: unless-stopped
    ports:
      - 3200:1200
    environment:
      - NODE_ENV=production
      - CACHE_TYPE=redis
      - REDIS_URL=redis://redis:6379/
      - PUPPETEER_WS_ENDPOINT=ws://browserless:3000
    depends_on:
      - redis
      - browserless

  browserless:
    image: browserless/chrome
    container_name: chrome
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
