version: '3'

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: always
    volumes:
      - ./data:/media:rw # 媒体文件夹
      - ./config:/config # 配置文件路径
      - ./transcode:/transcode # 转码临时文件路径
    environment:
      - PLEX_CLAIM="claim-tocken" # 请更改 token，去 https://www.plex.tv/claim/ 申请
      - TZ=Asia/Shanghai
    hostname: 'MB-plex-server' # 更改为你喜欢的名字
    ports:
      - 32400:32400/tcp # web 端口，必须的
      # 下面的端口是可选的 https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
      # - 3005:3005/tcp
      # - 8324:8324/tcp
      # - 32469:32469/tcp
      # - 1900:1900/udp
      # - 32410:32410/udp
      # - 32412:32412/udp
      # - 32413:32413/udp
      # - 32414:32414/udp
