version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: always
    ports:
      - 181:80
    volumes:
      - ./data:/srv # 根目录
      - ./.filebrowser.json:/.filebrowser.json
      - ./database.db:/database.db
    environment:
      - username=admin # 初始设置用户名
      - password=admin # 初始设置密码
      - port=80
      - log=stdout
      - database=/database.db
      - root=/srv
