version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password # 数据库密码
      - POSTGRES_USER=nextcloud

  app:
    image: nextcloud:fpm-alpine
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=password # 数据库密码，同上
      - POSTGRES_USER=nextcloud

    depends_on:
      - db

  web:
    build: ./web
    restart: always
    ports:
      - 3600:80
    volumes:
      - ./nextcloud:/var/www/html:ro
    depends_on:
      - app

volumes:
  db:
  nextcloud:
