version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf:/etc/nginx/conf.d:ro
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./html:/usr/share/nginx/html:ro
      - ./log:/var/log/nginx
